// <auto-generated />
namespace NCShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitDB2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDB2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803242017597_InitDB2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
